name: '${name}'
main: kr.jimin.screens.NexoScreens
version: '${version}'
api-version: 1.17
author: '${author}'
website: https://discord.gg/w63c637bmr
depend:
  - Nexo
  - ProtocolLib
softdepend:
  - PlaceholderAPI

commands:
  nexoscreens:
    aliases:
      - nexos
      - ns
    description: NexoScreens effects command
    permission: nexoscreens.admin

permissions:
  nexoscreens.admin:
    description: NexoScreens effects permissions
    default: op